# Weekly Issue creation and closure for Friday Snippets
# Inspired by the work of Steve Winton (@swinton) and John Bohannon (@imjohnbo)
# Source at:
# https://github.com/imjohnbo/issue-bot/blob/master/index.js
# Example at:
# https://github.com/github/partner-engineering/blob/c6d8f85a76b2d8a7188833537726043cd3dbdd52/.github/workflows/monthly-radar.yml

name: Friday Snippets Issue
on:
  schedule:
    # Run each Sunday at 1600 UTC
    - cron: "4 16 * * 0"

jobs:

  weekly-Friday-Snippets:
    name: Friday Snippets
    runs-on: ubuntu-latest
    steps:
      - name: Set Date
        run: echo "::set-env name=DATE::$(date -u '+%F')"
      
      - name: Friday-Snippets-issue-management
        uses: imjohnbo/issue-bot@v2.2
        with:
          title: "XRLT Friday Snippets week of ${{ env.DATE }}"
          template: ".github/ISSUE_TEMPLATE/Friday-Snippets-template.md"
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
